generatorName: csharp-netcore
additionalProperties:
  clientPackage: HelloSign.Api
  packageName: HelloSign
  packageAuthors: HelloSign
  packageCompany: HelloSign
  packageDescription: Client library for using the HelloSign API
  packageVersion: 6.0.0-beta.3
  packageTitle: HelloSign .Net SDK
  gitHost: github.com
  gitUserId: hellosign
  gitRepoId: hellosign-dotnet-sdk
  sortModelPropertiesByRequiredFlag: true
  optionalEmitDefaultValues: true
  targetFramework: net6.0
  packageGuid: "{F8C8232D-7020-4603-8E04-18D060AE530B}"
globalProperties:
  apiTests: false
  modelTests: false
